name: build-native-wheel
description: "Builds wheel natively"
runs:
  using: composite
  steps:
  - shell: bash
    run: python setup.py bdist_wheel
    env:
      RPYBUILD_PARALLEL: 1
      RPYBUILD_STRIP_LIBPYTHON: 1
