---
name: test-native-wheel
description: "Installs built wheel and runs tests"
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      cd dist
      python -m pip --disable-pip-version-check install *.whl
      cd ../tests
      python -m pip --disable-pip-version-check install -r requirements.txt
      python run_tests.py
